import React,{useRef,useState,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas} from '@react-three/fiber';
import {OrbitControls,Grid,Environment,TransformControls,useGLTF} from '@react-three/drei';
import {Box,Film,Music,Type,Layers,Settings,Play,Pause,Plus,Upload,Undo2,Redo2,Save,Download,Trash2,MousePointer2,Move3d,Circle,Square,Rotate3d,Maximize2} from 'lucide-react';
import './styles.css';
const tools=[['Media',Upload],['3D Objects',Box],['Text',Type],['Audio',Music],['Effects',Layers]];
const kind=f=>f.type.startsWith('video')?'video':f.type.startsWith('image')?'image':f.type.startsWith('audio')?'audio':/\.(glb|gltf|obj)$/i.test(f.name)?'model':'file';
function Model({asset,onSelect}){const {scene}=useGLTF(asset.url);const clone=useMemo(()=>scene.clone(true),[scene]);return <primitive object={clone} scale={asset.scale} position={asset.position} onClick={e=>{e.stopPropagation();onSelect(asset.id)}}/>}
function Primitive({asset,onSelect}){const geo=asset.shape==='sphere'?<sphereGeometry args={[1,24,16]}/>:asset.shape==='plane'?<planeGeometry args={[2,2]}/>:<boxGeometry args={[1.6,1.2,1.1]}/>;return <mesh position={asset.position} rotation={asset.rotation} scale={asset.scale} onClick={e=>{e.stopPropagation();onSelect(asset.id)}}>{geo}<meshStandardMaterial color="#8d98aa" metalness={.2} roughness={.5}/></mesh>}
function SceneObject({asset,onSelect,selected,transformMode,setTransformMode}){const ref=useRef();const content=asset.kind==='model'?<Model asset={asset} onSelect={onSelect}/>:asset.kind==='primitive'?<Primitive asset={asset} onSelect={onSelect}/>:<mesh ref={ref} position={asset.position} scale={asset.scale} onClick={e=>{e.stopPropagation();onSelect(asset.id)}}><boxGeometry args={[1.6,1,0.08]}/><meshStandardMaterial metalness={.15} roughness={.55}/></mesh>;return <>{content}{selected&&<TransformControls object={ref} mode={transformMode} onObjectChange={()=>{}}/></>}
}
function Viewport({assets,selected,setSelected,transformMode}){return <Canvas camera={{position:[4,3,6],fov:45}} dpr={[1,1.35]} gl={{antialias:true}} onPointerMissed={()=>setSelected(null)}><color attach="background" args={['#080a0f']}/><ambientLight intensity={.7}/><directionalLight position={[4,6,4]} intensity={2}/><Grid args={[20,20]} cellSize={1} cellThickness={.5} sectionSize={5} sectionThickness={1} fadeDistance={28} fadeStrength={1}/><Environment preset="city"/><OrbitControls makeDefault enableDamping/><group>{assets.map(a=><SceneObject key={a.id} asset={a} selected={selected===a.id} onSelect={setSelected} transformMode={transformMode}/>)}</group>{!assets.length&&<mesh><boxGeometry args={[1.5,1.5,1.5]}/><meshStandardMaterial wireframe/></mesh>}</Canvas>}
function App(){const [active,setActive]=useState('Media'),[playing,setPlaying]=useState(false),[assets,setAssets]=useState([]),[selected,setSelected]=useState(null),[project,setProject]=useState('Untitled Project'),[transformMode,setTransformMode]=useState('translate');const input=useRef();
 const addFiles=e=>{const files=Array.from(e.target.files||[]);setAssets(a=>[...a,...files.map(f=>({id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,kind:kind(f),url:URL.createObjectURL(f),position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}))]);e.target.value=''};
 const addPrimitive=shape=>{const id=crypto.randomUUID();setAssets(a=>[...a,{id,name:shape[0].toUpperCase()+shape.slice(1),type:'3d',size:0,kind:'primitive',shape,url:null,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}]);setSelected(id)};
 const remove=id=>{setAssets(a=>a.filter(x=>x.id!==id));if(selected===id)setSelected(null)};const updateSelected=(key,value)=>setAssets(a=>a.map(x=>x.id===selected?{...x,[key]:value}:x));const sel=assets.find(a=>a.id===selected);
 return <div className="app"><header><div className="brand"><div className="logo">D</div><div><b>DepthCut</b><small>3D VIDEO EDITOR</small></div></div><input className="project" value={project} onChange={e=>setProject(e.target.value)}/><div className="actions"><button title="Undo"><Undo2/></button><button title="Redo"><Redo2/></button><button><Save/> <span>Save</span></button><button className="export"><Download/> <span>Export</span></button></div></header>
 <div className="workspace"><aside className="sidebar">{tools.map(([n,I])=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}><I/><span>{n}</span></button>)}<div className="spacer"/><button><Settings/><span>Settings</span></button></aside>
 <section className="assets"><div className="panelTitle"><b>{active}</b><label className="add"><Plus/> Add Media<input ref={input} type="file" multiple accept="video/*,image/*,audio/*,.glb,.gltf,.obj" onChange={addFiles}/></label></div>{active==='3D Objects'&&<div className="primitiveBar"><button onClick={()=>addPrimitive('cube')}><Box/>Cube</button><button onClick={()=>addPrimitive('sphere')}><Circle/>Sphere</button><button onClick={()=>addPrimitive('plane')}><Square/>Plane</button></div>}<div className="assetGrid">{assets.map(a=><div className={'asset '+(selected===a.id?'selected':'')} key={a.id} onClick={()=>setSelected(a.id)}><div className="thumb">{a.kind==='video'&&<video src={a.url} muted/>}{a.kind==='image'&&<img src={a.url} alt=""/>}{a.kind==='audio'&&<Music/>}{a.kind==='model'&&<Box/>}{a.kind==='primitive'&&(a.shape==='sphere'?<Circle/>:a.shape==='plane'?<Square/>:<Box/>)}{a.kind==='file'&&<Film/>}</div><span title={a.name}>{a.name}</span><button className="assetDelete" onClick={e=>{e.stopPropagation();remove(a.id)}}><Trash2/></button></div>)}{!assets.length&&<div className="empty" onClick={()=>input.current?.click()}><Upload/><b>Import your media</b><small>Video · Images · Audio · GLB · GLTF · OBJ</small></div>}</div></section>
 <main className="viewport"><div className="viewportTop"><span>Perspective</span><span className="transformTools"><button onClick={()=>setTransformMode('translate')} className={transformMode==='translate'?'activeTool':''}><Move3d/></button><button onClick={()=>setTransformMode('rotate')} className={transformMode==='rotate'?'activeTool':''}><Rotate3d/></button><button onClick={()=>setTransformMode('scale')} className={transformMode==='scale'?'activeTool':''}><Maximize2/></button></span></div><div className="scene"><Viewport assets={assets} selected={selected} setSelected={setSelected} transformMode={transformMode}/><div className="hint"><MousePointer2/> DRAG · PINCH ZOOM · SELECT</div></div><div className="transport"><button onClick={()=>setPlaying(!playing)}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><span>00:00:00:00</span><div className="scrub"/></div></main>
 <aside className="inspector"><div className="panelTitle"><b>Inspector</b></div>{sel?<div className="properties"><b>Selected object</b><p title={sel.name}>{sel.name}</p><div className="propertyGrid"><label>X<input type="number" value={sel.position[0]} onChange={e=>updateSelected('position',[+e.target.value,sel.position[1],sel.position[2]])}/></label><label>Y<input type="number" value={sel.position[1]} onChange={e=>updateSelected('position',[sel.position[0],+e.target.value,sel.position[2]])}/></label><label>Z<input type="number" value={sel.position[2]} onChange={e=>updateSelected('position',[sel.position[0],sel.position[1],+e.target.value])}/></label></div><div className="propertyGrid"><label>Rot X<input type="number" value={sel.rotation[0]} onChange={e=>updateSelected('rotation',[+e.target.value,sel.rotation[1],sel.rotation[2]])}/></label><label>Rot Y<input type="number" value={sel.rotation[1]} onChange={e=>updateSelected('rotation',[sel.rotation[0],+e.target.value,sel.rotation[2]])}/></label><label>Rot Z<input type="number" value={sel.rotation[2]} onChange={e=>updateSelected('rotation',[sel.rotation[0],sel.rotation[1],+e.target.value])}/></label></div><label>Uniform Scale<input type="number" value={sel.scale[0]} step="0.1" onChange={e=>updateSelected('scale',[+e.target.value,+e.target.value,+e.target.value])}/></label></div>:<div className="inspectorEmpty"><Layers/><b>No object selected</b><small>Select an object in the 3D viewport or Media panel.</small></div>}</aside></div>
 <footer className="timeline"><div className="timelineHead"><b>Timeline</b><span>00:00 / 00:00</span><div><button>+</button><button>−</button></div></div><div className="tracks"><div className="trackLabels"><span>🎥 Video 1</span><span>🧊 3D Scene</span><span>🔊 Audio 1</span></div><div className="ruler"><span>00:00</span><span>00:05</span><span>00:10</span><span>00:15</span><span>00:20</span></div><div className="trackArea">{assets.slice(0,8).map((a,i)=><div className={'clip '+(selected===a.id?'clipSelected':'')} key={a.id} style={{left:(i*12)+'%',width:'10%'}} onClick={()=>setSelected(a.id)}>{a.name}</div>)}<div className="playhead"/></div></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
