import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,Undo2,Redo2,Save,Download,Trash2,Plus,Play,Pause,SkipBack,SkipForward,Scissors,Type,Music,Layers,Settings,Volume2,VolumeX,Maximize2,GripVertical,SlidersHorizontal,RotateCw,Lock,ChevronDown,MonitorPlay,Copy,RefreshCw} from 'lucide-react';
import './styles.css';

const tools=[['Media',Upload],['Text',Type],['Overlay',Layers],['Effects',SlidersHorizontal],['Audio',Music]];
const kind=f=>f.type.startsWith('video/')?'video':f.type.startsWith('image/')?'image':f.type.startsWith('audio/')?'audio':'file';
const fmt=s=>{s=Math.max(0,Number(s)||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`};
const duration=a=>Math.max(.1,(a.end??a.duration??5)-(a.start??0));
const defaults={x:0,y:0,scale:100,rotation:0,opacity:100,brightness:100,contrast:100,saturate:100,blur:0,speed:1,volume:1,filter:'none'};
const normalize=a=>({...defaults,...a});

function App(){
 const [active,setActive]=useState('Media'),[assets,setAssets]=useState([]),[selected,setSelected]=useState(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[project,setProject]=useState('Untitled Project'),[text,setText]=useState(''),[zoom,setZoom]=useState(1),[aspect,setAspect]=useState('16:9'),[volume,setVolume]=useState(1),[muted,setMuted]=useState(false),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[snap,setSnap]=useState(true),[mediaFilter,setMediaFilter]=useState('All'),[fullscreen,setFullscreen]=useState(false);
 const input=useRef(),video=useRef(),audio=useRef(),drag=useRef(null);
 const selectedAsset=assets.find(a=>a.id===selected);
 const primary=assets.find(a=>a.kind==='video')||assets.find(a=>a.kind==='image')||assets[0];
 const previewAsset=selectedAsset?.kind==='video'?selectedAsset:primary;
 const total=Math.max(1,assets.reduce((m,a)=>Math.max(m,(a.start||0)+duration(a)),0));
 const pushHistory=next=>{setHistory(h=>[...h,assets].slice(-30));setFuture([]);setAssets(next)};
 const update=id=>patch=>pushHistory(assets.map(a=>a.id===id?{...a,...patch}:a));
 const addFiles=e=>{const files=[...e.target.files||[]];if(!files.length)return;const next=files.map(f=>normalize({id:crypto.randomUUID(),name:f.name,type:f.type,size:f.size,kind:kind(f),url:URL.createObjectURL(f),duration:f.type.startsWith('image/')?5:0,start:0,end:f.type.startsWith('image/')?5:0}));pushHistory([...assets,...next]);setSelected(next[0].id);e.target.value=''};
 const remove=id=>{const x=assets.find(a=>a.id===id);if(x?.url)URL.revokeObjectURL(x.url);pushHistory(assets.filter(a=>a.id!==id));if(selected===id){setSelected(null);setPlaying(false);setTime(0)}};
 const choose=id=>{video.current?.pause();audio.current?.pause();setPlaying(false);setTime(0);setSelected(id)};
 const seekGlobal=t=>{const next=Math.max(0,Math.min(total,t));setTime(next);if(video.current&&previewAsset?.kind==='video')video.current.currentTime=Math.min(video.current.duration||next,next);if(audio.current&&selectedAsset?.kind==='audio')audio.current.currentTime=Math.max(0,next-(selectedAsset.start||0))};
 const toggle=()=>{if(!previewAsset)return;if(previewAsset.kind==='video'){if(!video.current)return;playing?video.current.pause():video.current.play().catch(()=>{});return}if(previewAsset.kind==='audio'&&audio.current){playing?audio.current.pause():audio.current.play().catch(()=>{});return}setPlaying(p=>!p)};
 const addText=()=>{const value=text.trim()||'Your Text';const id=crypto.randomUUID();pushHistory([...assets,normalize({id,name:value,type:'text',kind:'text',duration:5,start:0,end:5,text:value,fontSize:42,color:'#ffffff',fontWeight:700})]);setSelected(id);setText('')};
 const splitSelected=()=>{if(!selectedAsset)return;const start=selectedAsset.start||0,end=selectedAsset.end??selectedAsset.duration??5;const cut=Math.max(start+.05,Math.min(end-.05,time));if(cut<=start||cut>=end)return;const second=normalize({...selectedAsset,id:crypto.randomUUID(),name:`${selectedAsset.name} (2)`,start:cut,end});pushHistory(assets.flatMap(a=>a.id===selectedAsset.id?[normalize({...a,end:cut}),second]:[a]));setSelected(second.id);setTime(cut)};
 const duplicate=()=>{if(!selectedAsset)return;const id=crypto.randomUUID();const copy=normalize({...selectedAsset,id,name:`${selectedAsset.name} Copy`,start:(selectedAsset.start||0)+duration(selectedAsset),end:(selectedAsset.end??selectedAsset.duration??5)+duration(selectedAsset)});pushHistory([...assets,copy]);setSelected(id)};
 const moveClip=(id,delta)=>setAssets(a=>a.map(x=>x.id===id?{...x,start:Math.max(0,(x.start||0)+delta),end:Math.max((x.end??x.duration??5)+delta,(x.start||0)+delta+.1)}:x));
 const trimClip=(id,side,delta)=>setAssets(a=>a.map(x=>{if(x.id!==id)return x;const start=x.start||0,end=x.end??x.duration??5;if(side==='left')return {...x,start:Math.max(0,Math.min(end-.1,start+delta))};return {...x,end:Math.max(start+.1,Math.min(x.duration||end,end+delta))}}));
 const beginDrag=(e,id,mode,width)=>{e.preventDefault();e.stopPropagation();drag.current={id,mode,x:e.clientX,width:Math.max(1,width),total}};
 const filterStyle=a=>({filter:`brightness(${a.brightness??100}%) contrast(${a.contrast??100}%) saturate(${a.saturate??100}%) blur(${a.blur??0}px)`,opacity:(a.opacity??100)/100,transform:`translate(${a.x||0}px,${a.y||0}px) scale(${(a.scale||100)/100}) rotate(${a.rotation||0}deg)`,mixBlendMode:a.blend||'normal'});
 const undo=()=>{if(!history.length)return;setFuture(f=>[assets,...f].slice(0,30));setAssets(history[history.length-1]);setHistory(h=>h.slice(0,-1))};
 const redo=()=>{if(!future.length)return;setHistory(h=>[...h,assets].slice(-30));setAssets(future[0]);setFuture(f=>f.slice(1))};
 useEffect(()=>{const up=e=>{const q=drag.current;if(!q)return;const dx=(e.clientX-q.x)/q.width*q.total;q.x=e.clientX;if(q.mode==='move')moveClip(q.id,dx);else trimClip(q.id,q.mode,dx)};const end=()=>{drag.current=null};window.addEventListener('pointermove',up);window.addEventListener('pointerup',end);return()=>{window.removeEventListener('pointermove',up);window.removeEventListener('pointerup',end)}},[total]);
 useEffect(()=>{const key=e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();toggle()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}if(e.key==='Delete'&&selectedAsset)remove(selectedAsset.id)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 useEffect(()=>{if(video.current){video.current.muted=muted;video.current.volume=volume;video.current.playbackRate=selectedAsset?.speed||1}if(audio.current){audio.current.muted=muted;audio.current.volume=volume;audio.current.playbackRate=selectedAsset?.speed||1}},[muted,volume,selectedAsset]);
 useEffect(()=>()=>assets.forEach(a=>a.url&&URL.revokeObjectURL(a.url)),[]);
 const toggleFullscreen=()=>{const el=document.querySelector('.previewArea');if(!document.fullscreenElement){el?.requestFullscreen?.().then(()=>setFullscreen(true)).catch(()=>{});}else{document.exitFullscreen?.().finally(()=>setFullscreen(false))}};
 useEffect(()=>{const onFs=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',onFs);return()=>document.removeEventListener('fullscreenchange',onFs)},[]);
 const overlayAssets=useMemo(()=>assets.filter(a=>(a.kind==='image'||a.kind==='text'||a.kind==='video')&&a.id!==previewAsset?.id&&time>=(a.start||0)&&time<=(a.end??a.duration??5)),[assets,time,previewAsset]);
 return <div className="app">
  <header><div className="brand"><div className="logo">D</div><div><b>DepthCut</b><small>VIDEO EDITOR</small></div></div><div className="topMenu"><span>File</span><span>Edit</span><span>Help</span></div><div className="projectWrap"><input className="project" value={project} onChange={e=>setProject(e.target.value)}/><span>✎</span></div><div className="actions"><button title="Undo" onClick={undo}><Undo2/></button><button title="Redo" onClick={redo}><Redo2/></button><button onClick={()=>localStorage.setItem('depthcut-project',JSON.stringify({project,assets:assets.map(({url,...a})=>a)}))}><Save/><span>Save</span></button><button className="export" onClick={()=>previewAsset?.url&&Object.assign(document.createElement('a'),{href:previewAsset.url,download:previewAsset.name}).click()}><Download/><span>Export</span></button></div></header>
  <div className="editor">
   <aside className="sidebar">{tools.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><I/><span>{n}</span></button>)}<div className="spacer"/><button><Settings/><span>Settings</span></button></aside>
   <section className="mediaPanel"><div className="panelTitle"><b>{active}</b>{active==='Media'&&<label className="add"><Plus/> Add Media<input ref={input} type="file" multiple accept="video/*,image/*,audio/*" onChange={addFiles}/></label>}</div>
    {active==='Media'&&<><div className="mediaTabs">{['All','Video','Image','Audio'].map(tab=><span key={tab} className={mediaFilter===tab?'active':''} onClick={()=>setMediaFilter(tab)}>{tab}</span>)}</div><div className="assetGrid">{assets.filter(a=>a.kind!=='text'&&(mediaFilter==='All'||a.kind===mediaFilter.toLowerCase())).map(a=><div className={'asset '+(selected===a.id?'selected':'')} key={a.id} onClick={()=>choose(a.id)}><div className="thumb">{a.kind==='video'&&<video src={a.url} muted playsInline preload="metadata"/>}{a.kind==='image'&&<img src={a.url} alt="" loading="lazy"/>}{a.kind==='audio'&&<Music/>}</div><span title={a.name}>{a.name}</span><button className="assetDelete" onClick={e=>{e.stopPropagation();remove(a.id)}}><Trash2/></button></div>)}{!assets.length&&<div className="empty" onClick={()=>input.current?.click()}><Upload/><b>Import videos, photos & audio</b><small>MP4 · MOV · WebM · JPG · PNG · MP3 · WAV</small></div>}</div></>}
    {active==='Text'&&<div className="toolBox"><h3>Text</h3><input value={text} onChange={e=>setText(e.target.value)} placeholder="Enter text"/><button className="primary" onClick={addText}><Plus/> Add to timeline</button><hr/><p>Text is editable from Inspector after selecting the text clip.</p></div>}
    {active==='Overlay'&&<div className="toolBox"><h3>Overlay</h3><p>Select image/video in Media. Its timeline position controls when it appears over the main video.</p></div>}
    {active==='Audio'&&<div className="toolBox"><h3>Audio</h3><p>Import MP3/WAV and select the audio clip to control volume and speed.</p></div>}
    {active==='Effects'&&<div className="toolBox"><h3>Effects</h3><button onClick={()=>selectedAsset&&update(selectedAsset.id)({brightness:100,contrast:100,saturate:100,blur:0})}>Reset adjustments</button><button onClick={()=>selectedAsset&&update(selectedAsset.id)({brightness:115})}>Bright</button><button onClick={()=>selectedAsset&&update(selectedAsset.id)({contrast:125,saturate:110})}>Cinematic</button><button onClick={()=>selectedAsset&&update(selectedAsset.id)({saturate:0,contrast:115})}>B&W</button><button onClick={()=>selectedAsset&&update(selectedAsset.id)({blur:4})}>Soft Blur</button></div>}
   </section>
   <main className="previewArea"><div className="previewToolbar"><div><button className="aspectBtn" onClick={()=>setAspect(a=>a==='16:9'?'9:16':'16:9')}>{aspect}⌄</button><button onClick={()=>setZoom(1)}><RefreshCw/></button></div><span>{fullscreen?'Fullscreen preview':'Preview'}</span><button title="Fullscreen" onClick={toggleFullscreen}><Maximize2/></button></div><div className={'previewStage ratio-'+aspect.replace(':','x')} style={{'--previewZoom':zoom}}>
    {previewAsset?.kind==='video'&&<video ref={video} className="previewMedia" style={filterStyle(previewAsset)} src={previewAsset.url} playsInline preload="metadata" onLoadedMetadata={e=>{if(!previewAsset.duration)update(previewAsset.id)({duration:e.currentTarget.duration,end:e.currentTarget.duration});e.currentTarget.currentTime=Math.min(e.currentTarget.duration,time)}} onTimeUpdate={e=>{setTime(Math.min(total,e.currentTarget.currentTime));if(e.currentTarget.ended)setPlaying(false)}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}/>} 
    {previewAsset?.kind==='image'&&<img className="previewMedia" style={filterStyle(previewAsset)} src={previewAsset.url} alt="Preview"/>}
    {previewAsset?.kind==='audio'&&<><div className="audioPreview"><Music/><b>{previewAsset.name}</b></div><audio ref={audio} src={previewAsset.url} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/></>}
    {overlayAssets.map(a=>a.kind==='text'?<div key={a.id} className="textPreview" style={{...filterStyle(a),fontSize:a.fontSize||42,color:a.color||'#fff',fontWeight:a.fontWeight||700}}>{a.text}</div>:a.kind==='video'?<video key={a.id} className="previewMedia overlayPreview" style={filterStyle(a)} src={a.url} muted playsInline autoPlay loop/>:<img key={a.id} className="previewMedia overlayPreview" style={filterStyle(a)} src={a.url} alt="Overlay"/>)}
    {!previewAsset&&<div className="previewEmpty"><MonitorPlay/><b>Start editing</b><span>Import a video or photo</span></div>}
   </div><div className="scrubber"><input type="range" min="0" max={total} step="0.01" value={Math.min(total,time)} onChange={e=>seekGlobal(Number(e.target.value))}/></div><div className="transport"><button onClick={()=>seekGlobal(0)}><SkipBack/></button><button className="play" onClick={toggle}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button onClick={()=>seekGlobal(Math.min(total,time+5))}><SkipForward/></button><span>{fmt(time)} / {fmt(total)}</span><div className="transportSpace"/><Volume2/><input className="volume" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><button onClick={()=>setMuted(v=>!v)}>{muted?<VolumeX/>:<Volume2/>}</button></div></main>
   <Inspector selectedAsset={selectedAsset} update={update} duplicate={duplicate}/>
  </div>
  <footer className="timeline"><div className="editToolbar"><button onClick={splitSelected}><Scissors/> Split</button><button onClick={()=>selectedAsset&&remove(selectedAsset.id)}><Trash2/> Delete</button><button onClick={duplicate}><Copy/> Duplicate</button><button onClick={()=>selectedAsset&&update(selectedAsset.id)({speed:Math.min(2,(selectedAsset.speed||1)+.25)})}><RotateCw/> Speed</button><button onClick={()=>setActive('Effects')}><SlidersHorizontal/> Filters</button><div className="timelineZoom"><button onClick={()=>setZoom(Math.max(.5,zoom-.1))}>−</button><input type="range" min=".5" max="1.5" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><button onClick={()=>setZoom(Math.min(1.5,zoom+.1))}>+</button></div></div><div className="timelineHead"><div><b>Timeline</b><span>{fmt(time)} / {fmt(total)}</span></div><div className="timelineTools"><button title="Snap" className={snap?'active':''} onClick={()=>setSnap(s=>!s)}><Lock/></button></div></div><div className="timelineBody"><div className="trackLabels"><span>🎬 Video 1</span><span>▧ Overlay 1</span><span>🔊 Audio 1</span></div><div className="trackScroll"><div className="ruler">{Array.from({length:11},(_,i)=><span key={i}>{fmt(i*2)}</span>)}</div><div className="tracks" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();seekGlobal(((e.clientX-r.left)/r.width)*total)}}>
    {assets.filter(a=>a.kind==='video').map(a=><TimelineClip key={a.id} a={a} selected={selected===a.id} onSelect={choose} beginDrag={beginDrag} total={total} remove={remove}/>) }
    {assets.filter(a=>a.kind==='image'||a.kind==='text').map(a=><TimelineClip key={a.id} a={a} selected={selected===a.id} onSelect={choose} beginDrag={beginDrag} total={total} remove={remove} overlay/>)}
    {assets.filter(a=>a.kind==='audio').map(a=><TimelineClip key={a.id} a={a} selected={selected===a.id} onSelect={choose} beginDrag={beginDrag} total={total} remove={remove} audio/>)}
    <div className="timelineCursor" style={{left:`${Math.min(99.5,Math.max(0,(time/total)*100))}%`}}/>
   </div></div></div></footer>
 </div>
}
function Inspector({selectedAsset:a,update,duplicate}){if(!a)return <aside className="inspector"><div className="inspectorHead"><b>Inspector</b></div><div className="inspectorEmpty">Select a clip to edit it.</div></aside>;const patch=p=>update(a.id)(p);return <aside className="inspector"><div className="inspectorHead"><b>{a.kind==='audio'?'Audio':a.kind==='image'?'Image':a.kind==='text'?'Text':'Video'}</b><button onClick={duplicate}><Copy/></button></div><InspectorSection title="Transform"><InspectorRange label="Scale" min="20" max="200" value={a.scale} suffix="%" onChange={v=>patch({scale:v})}/><div className="twoFields"><label>X<input type="number" value={a.x} onChange={e=>patch({x:Number(e.target.value)||0})}/></label><label>Y<input type="number" value={a.y} onChange={e=>patch({y:Number(e.target.value)||0})}/></label></div><InspectorRange label="Rotation" min="-180" max="180" value={a.rotation} suffix="°" onChange={v=>patch({rotation:v})}/></InspectorSection><InspectorSection title="Opacity & Color"><InspectorRange label="Opacity" value={a.opacity} suffix="%" onChange={v=>patch({opacity:v})}/><InspectorRange label="Brightness" min="50" max="150" value={a.brightness} suffix="%" onChange={v=>patch({brightness:v})}/><InspectorRange label="Contrast" min="50" max="150" value={a.contrast} suffix="%" onChange={v=>patch({contrast:v})}/><InspectorRange label="Saturation" min="0" max="200" value={a.saturate} suffix="%" onChange={v=>patch({saturate:v})}/><InspectorRange label="Blur" min="0" max="12" value={a.blur} suffix="px" onChange={v=>patch({blur:v})}/></InspectorSection>{a.kind==='text'&&<InspectorSection title="Text"><input className="wideButton" value={a.text||''} onChange={e=>patch({text:e.target.value,name:e.target.value})}/><InspectorRange label="Size" min="12" max="120" value={a.fontSize||42} suffix="px" onChange={v=>patch({fontSize:v})}/></InspectorSection>}{(a.kind==='video'||a.kind==='audio')&&<InspectorSection title="Playback"><InspectorRange label="Speed" min="25" max="200" value={(a.speed||1)*100} suffix="%" onChange={v=>patch({speed:v/100})}/><InspectorRange label="Volume" min="0" max="100" value={(a.volume??1)*100} suffix="%" onChange={v=>patch({volume:v/100})}/></InspectorSection>}<InspectorSection title="Blend"><select className="wideButton" value={a.blend||'normal'} onChange={e=>patch({blend:e.target.value})}><option value="normal">Normal</option><option value="multiply">Multiply</option><option value="screen">Screen</option><option value="overlay">Overlay</option></select></InspectorSection></aside>}
function InspectorSection({title,children}){return <section className="inspectorSection"><div className="sectionTitle"><b>{title}</b><ChevronDown/></div>{children}</section>}
function InspectorRange({label,min=0,max=100,value,suffix,onChange}){return <label className="rangeRow"><span>{label}</span><input type="range" min={min} max={max} value={value??min} onChange={e=>onChange(Number(e.target.value))}/><b>{Math.round(value??min)}{suffix}</b></label>}
function TimelineClip({a,selected,onSelect,beginDrag,total,remove,overlay,audio}){const width=Math.max(4,(duration(a)/total)*100),left=((a.start||0)/total)*100,row=audio?'audioClip':overlay?'overlayClip':'videoClip';return <div className={'clip '+row+(selected?' selectedClip':'')} style={{left:`${left}%`,width:`${width}%`}} onPointerDown={e=>beginDrag(e,a.id,'move',e.currentTarget.parentElement.clientWidth)} onClick={e=>{e.stopPropagation();onSelect(a.id)}}><button className="trimHandle left" onPointerDown={e=>beginDrag(e,a.id,'left',e.currentTarget.parentElement.parentElement.clientWidth)}/><GripVertical className="dragIcon"/>{a.kind==='video'&&<video src={a.url} muted preload="metadata"/>}{a.kind==='image'&&<img src={a.url} alt=""/>}{a.kind==='text'&&<Type/>}{audio&&<Music/>}<span>{a.name}</span><button className="clipDelete" onClick={e=>{e.stopPropagation();remove(a.id)}}><Trash2/></button><button className="trimHandle right" onPointerDown={e=>beginDrag(e,a.id,'right',e.currentTarget.parentElement.parentElement.clientWidth)}/></div>}
createRoot(document.getElementById('root')).render(<App/>);
